### ISSUE TITLE
Installed on R x64 3.6.2

### ISSUE THREAD

**Issue by ssabat** [zappingseb/coronashiny#1]
Hi Sebastian,

I was able to install coronashine on Windows  Rx64 3.6.2 following your instructions. Thanks for good work. Here is a snapshot.

![coronashiny](https://user-images.githubusercontent.com/519533/78454024-4aa1da00-764a-11ea-948f-301af9dcc1b0.JPG)

I had couple of questions:

1. Why the  slider goes to April 2, not April 3?
2. Can we add Zero Day analytics  chart  i.e rate of growth since first occurrence? I know you already have captured the data for for all countries. Renaming would do it.

In stead of saying CSEE update on lower right corner,  you can splash a big  message saying -           " Wait! Data Sets Updating. "

Sunil

**Comment by zappingseb** [comment]
Hi @ssabat ,

First Question 2:
Hm, I did not really think of charts for "What happened from Day 0?", yet. Maybe I'll add this. I'll make it a separate issue #2, ok! Currently, such numbers are only inside the table.

Question 1:
This might have been due to missing daily report "04-03-2020.csv" inside here: https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data/csse_covid_19_daily_reports
Please run `git pull` inside `shiny/COVID-19` again and see if it arrives. Locally the `git pull` does not always update. I did not understand, yet, why this is the case. On shinyapps.io it works fine.

Last:
Good Idea with the big message! But I hope data loading does not take too long :)

Take care,

Sebastian

**Comment by zappingseb** [comment]
Ah @ssabat, can you add some more details into #2?? Please
